# Generated by Django 5.0.6 on 2024-07-01 11:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f92e4c4-63fd-412a-bf97-753a93b5c988'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2f92e4c4-63fd-412a-bf97-753a93b5c988'), editable=False, primary_key=True, serialize=False),
        ),
    ]
