# Generated by Django 5.0.6 on 2024-07-03 10:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7c6cbdf-3a22-4c57-960e-9f9f89dc86cb'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7c6cbdf-3a22-4c57-960e-9f9f89dc86cb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
