# Generated by Django 5.0.6 on 2024-07-03 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b2681b2-837d-4956-af50-044f0fd22e45'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2b2681b2-837d-4956-af50-044f0fd22e45'), editable=False, primary_key=True, serialize=False),
        ),
    ]
