# Generated by Django 5.0.6 on 2024-07-03 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3ce6c10-38fd-4cb7-ad31-f7943b77a360'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c3ce6c10-38fd-4cb7-ad31-f7943b77a360'), editable=False, primary_key=True, serialize=False),
        ),
    ]
