# Generated by Django 5.0.6 on 2024-07-03 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id_alter_userconfirmation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('050869e4-786a-4909-8e7e-cbda09d926c3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userconfirmation',
            name='id',
            field=models.UUIDField(default=uuid.UUID('050869e4-786a-4909-8e7e-cbda09d926c3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
